version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    volumes:
      - .:/app
  db:
    image: mysql:latest
    restart: always
    container_name: 'mySql_container'
    environment:
      MYSQL_DATABASE: 'demoDB'
      MYSQL_USER: 'itsmart'
      MYSQL_PASSWORD: 'itsmart1!'
      MYSQL_ROOT_PASSWORD: 'itsmart1!'
      TZ: Asia/Seoul
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
volumes:
  db:
